language: node_js
node_js:
- stable

git:
  submodules: false

branches:
  only:
  - master

script: make build-deploy

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: static
  on:
    branch: master